-- public.tbl_games definition

-- Drop table

-- DROP TABLE public.tbl_games;

CREATE TABLE public.tbl_games (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	description varchar(255) NULL,
	"name" varchar(255) NULL,
	CONSTRAINT tbl_games_pkey PRIMARY KEY (id)
);


-- public.tbl_players definition

-- Drop table

-- DROP TABLE public.tbl_players;

CREATE TABLE public.tbl_players (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	image varchar(255) NULL,
	"name" varchar(255) NOT NULL,
	CONSTRAINT tbl_players_pkey PRIMARY KEY (id)
);


-- public.tbl_answer_groups definition

-- Drop table

-- DROP TABLE public.tbl_answer_groups;

CREATE TABLE public.tbl_answer_groups (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(255) NULL,
	game_id int4 NULL,
	CONSTRAINT tbl_answer_groups_pkey PRIMARY KEY (id),
	CONSTRAINT fkg1buo16vfos9osw2ly84u310n FOREIGN KEY (game_id) REFERENCES tbl_games(id)
);


-- public.tbl_answers definition

-- Drop table

-- DROP TABLE public.tbl_answers;

CREATE TABLE public.tbl_answers (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"content" varchar(255) NULL,
	content_as_image varchar(255) NULL,
	answer_group_id int4 NOT NULL,
	CONSTRAINT tbl_answers_pkey PRIMARY KEY (id),
	CONSTRAINT fkbdr5m82d7su30wvty1x0jm18y FOREIGN KEY (answer_group_id) REFERENCES tbl_answer_groups(id)
);


-- public.tbl_game_boards definition

-- Drop table

-- DROP TABLE public.tbl_game_boards;

CREATE TABLE public.tbl_game_boards (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	code varchar(50) NOT NULL,
	game_id int4 NOT NULL,
	CONSTRAINT tbl_game_boards_pkey PRIMARY KEY (id),
	CONSTRAINT uk_pp3nijdebq9jd016eyh2gm8cq UNIQUE (code),
	CONSTRAINT fk1ylk50aruc8mai4lp94mo53t6 FOREIGN KEY (game_id) REFERENCES tbl_games(id)
);


-- public.tbl_questions definition

-- Drop table

-- DROP TABLE public.tbl_questions;

CREATE TABLE public.tbl_questions (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"content" varchar(255) NULL,
	image varchar(255) NULL,
	answer_group_id int4 NOT NULL,
	game_id int4 NULL,
	CONSTRAINT tbl_questions_pkey PRIMARY KEY (id),
	CONSTRAINT fk4wvlmdl3jags539kdh2wns30i FOREIGN KEY (game_id) REFERENCES tbl_games(id),
	CONSTRAINT fkesferi345dikoqbd8aot4oecd FOREIGN KEY (answer_group_id) REFERENCES tbl_answer_groups(id)
);


-- public.tbl_answered_questions definition

-- Drop table

-- DROP TABLE public.tbl_answered_questions;

CREATE TABLE public.tbl_answered_questions (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"content" varchar(255) NULL,
	image varchar(255) NULL,
	answer_group_id int4 NOT NULL,
	game_board_id int4 NOT NULL,
	prefered_answer int4 NOT NULL,
	CONSTRAINT tbl_answered_questions_pkey PRIMARY KEY (id),
	CONSTRAINT fkc9parpcgrwql8633uh4pj6x33 FOREIGN KEY (answer_group_id) REFERENCES tbl_answer_groups(id),
	CONSTRAINT fkfp04vsb412he5e9s2a4fupmk8 FOREIGN KEY (prefered_answer) REFERENCES tbl_answers(id),
	CONSTRAINT fkkrwp7x0nk1uhxvkw7dv9f7xol FOREIGN KEY (game_board_id) REFERENCES tbl_game_boards(id)
);


-- public.tbl_game_board_players definition

-- Drop table

-- DROP TABLE public.tbl_game_board_players;

CREATE TABLE public.tbl_game_board_players (
	game_board_id int4 NOT NULL,
	player_id int4 NOT NULL,
	CONSTRAINT tbl_game_board_players_pkey PRIMARY KEY (game_board_id, player_id),
	CONSTRAINT fk23ykh6dvrkxemeuds2prf49q1 FOREIGN KEY (game_board_id) REFERENCES tbl_game_boards(id),
	CONSTRAINT fkq0egl79yr2ghek2540tw3xh32 FOREIGN KEY (player_id) REFERENCES tbl_players(id)
);


-- public.tbl_answered_question_details definition

-- Drop table

-- DROP TABLE public.tbl_answered_question_details;

CREATE TABLE public.tbl_answered_question_details (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	answer_id int4 NULL,
	answered_question_id int4 NULL,
	player_id int4 NULL,
	CONSTRAINT tbl_answered_question_details_pkey PRIMARY KEY (id),
	CONSTRAINT fk2blai0harpa4dfiecxyl7d238 FOREIGN KEY (answered_question_id) REFERENCES tbl_answered_questions(id),
	CONSTRAINT fkgygrv6fcvhr9e78xp1btatm6m FOREIGN KEY (player_id) REFERENCES tbl_players(id),
	CONSTRAINT fkhc99e78gja5rqrvsv67aqv0b0 FOREIGN KEY (answer_id) REFERENCES tbl_answers(id)
);